version : '3.8'

networks :
   net_calc:
     driver: bridge

services:
  front:
    build: ./frontend/code
    ports:
     - "3001:3001"
    networks:
      - net_calc

  back:
    build: ./backend/code
    ports:
      - "3002:3002"
    networks:
      -  net_calc
