version: "3.8"


networks:
  net_calc:
    driver: bridge

services:
  web:
    build: frontend/code/
    command: npm run start
    networks:
     - net_calc
    ports:
      - "3001:3001"
    develop:
      watch:
        - path: frontend/code/components
          action: sync
          target: app/components

  api:
    build: backend/code/
    networks:
      - net_calc
    ports:
      - "3002:3002"
    volumes:
      - /home/logs/calculadora:/app/logs
    develop:
      watch:
        - path: backend/code/data
          action: rebuild
          target: app/data

        - path: backend/code/utils
          action: rebuild
          target: app/utils
        
        - path: backend/code/conexos
          action: rebuild
          target: app/conexos

        - path: backend/code/route.py
          action: rebuild
          target: app/route.py
